version: 1

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - python -m uvicorn main:app --host 0.0.0.0 --port 8000

artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%d)
